### ISSUE TITLE
Fix Discordlog whitelist

### ISSUE THREAD

**Issue by infinityrueffel** [DreamInfinity/Issues#1]
At the moment the whitelist is only entered in the DB by the script but it must also be changed in the variable

**Comment by SpigotFehlerYT** [comment]
Funktioniert nicht ist nicht im Roleplay Script ich kann nicht auf die Variblen zu greifen ist im DiscordLog.
Wenn dann müssen wir das über das UCP machen mit der API die ich noch baue.
